version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: 7.4.1
#    logging:
#        driver: none
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: bind
        source: /var/lib/elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      ELASTIC_PASSWORD: A6fg7uiJ
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
      TZ: "Europe/Moscow"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: 7.4.1
#    logging:
#        driver: none
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
      - type: bind
        source: ./logstash/patterns
        target: /etc/logstash
      - type: bind
        source: ./logstash/certs
        target: /etc/logstash/certs
    ports:
      - "10514:10514/udp"
      - "514:514/udp"
      - "9600:9600"
      - "5044:5044"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      TZ: "Europe/Moscow"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: 7.4.1
#    logging:
#        driver: none
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    environment:
      TZ: "Europe/Moscow"
    networks:
      - elk
    depends_on:
      - elasticsearch

  elastalert:
        build:
          context: elastalert
        environment:
            ELASTIC_PWD: A6fg7uiJ
            ELASTICSEARCH_HOST: elasticsearch
            ELASTICSEARCH_PORT: 9200
        volumes:
            - /etc/elastalert:/etc/elastalert
            - ./elastalert/rules:/usr/share/elastalert/rules
        networks:
            - elk
        restart: unless-stopped

networks:
  elk:
    driver: bridge

#volumes:
#  elasticsearch:
#    driver: local
#    driver_opts:
#      type: bind
#      device: /var/lib/elasticsearc

 
  
